stages:
  train_model:
    cmd: python favicon_gen/call_training.py
    deps:
      - data/LLD-icon.hdf5
    outs:
      - outs/model.pt
    params:
      - general
      - model
      - dataset
    plots:
      - outs/loss.csv:
          x: Epoch
          y: Loss

  draw_samples:
    cmd: python favicon_gen/sample_from_model.py --use_gpu --n_samples 64
    deps:
      - outs/model.pt
    params:
    - dataset

metrics:
  - outs/metrics.json