stages:
  train_autoencoder:
    cmd: python logo_maker/autoencoder.py
    deps:
      - data/LLD-icon.hdf5
    outs:
      - outs/train_autoencoder/
    params:
      - logo_maker/params.py:
        - AutoEncoderParams
    plots:
      - outs/train_autoencoder/loss.csv:
          x: Epoch
          y: Loss
