name: favicon_gen

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - black=23
  - dvc>=3
  - flake8=6
  - h5py>=3.7
  - matplotlib>=3.7
  - mypy>=0.9
  - numpy>=1.25
  - pip
  - pylint>=2.16
  - pytest>=7.3
  - python>=3.10
  - pytorch-cuda=11.7
  - tqdm>=4.65
  - pytorch>=2
  - torchaudio>=2
  - torchvision>=0.15