dataset:
  name: LLD
  specific_clusters:
  - 0
  - 1
  - 2
  - 3
  n_images: 1000
  shuffle: true
model:
  adversarial_loss_weight: 1.0
  kl_loss_weight: 1.0
general:
  device: cuda
  do_norm: true
  embedding_dim: 32
  batch_size: 64
  epochs: 5
  learning_rate: 0.01
