dataset:
  name: LLD
  specific_clusters:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  n_images: 1
  shuffle: true
model:
  architecture: UNET2D
  guiding_factor: null
  steps: 1000
  var_schedule_start: 0.0001
  var_schedule_end: 0.02
general:
  device: cuda
  do_norm: true
  embedding_dim: 32
  batch_size: 128
  epochs: 10
  learning_rate: 0.0005
  lr_reduction_patience: 5
