dataset:
  name: LLD
  specific_clusters: null
  n_images: 50000
  shuffle: true
model:
  architecture: CUSTOM
  steps: 1000
  var_schedule_start: 0.0001
  var_schedule_end: 0.02
general:
  device: cuda
  do_norm: true
  embedding_dim: 32
  batch_size: 128
  epochs: 10
  learning_rate: 0.0002
  lr_reduction_patience: 2
