[tool.black]
line-length = 100

[tool.pylint]
max-line-length = 100
ignored-modules = ["numpy", "torch"]

[tool.pylint."messages control"]
disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "missing-module-docstring",
]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "."