defaults:
  - dataset: lld
  - _self_

general:
  device: "cuda"
  embedding_dim: 32
  do_norm: True

autoencoder:
  adversarial_loss_weight: 1.0
  batch_size: 512
  epochs_mnist: 20
  epochs_lld: 100
  kl_loss_weight: 1.0
  learning_rate: 4e-4

diffusion:
  batch_size: 32
  epochs_mnist: 20
  epochs_lld: 100
  guiding_factor: 0.90
  learning_rate: 1e-2
  steps: 1000
  var_schedule_start: 0.0001
  var_schedule_end: 0.02
