defaults:
  - dataset: lld
  - model: diffusion
  - _self_

general:
  device: "cuda"
  do_norm: True
  embedding_dim: 32
  batch_size: 128
  epochs: 10
  learning_rate: 0.5e-3
  lr_reduction_patience: 5